### PR TITLE
fixed it so my and probably other account names fit

### PR DESCRIPTION
**Pull request by ImaginaryDevelopment**
my account name wasn't allowed in these dialog boxes. as it is 30 characters

### CODE REVIEW

**Comment by brather1ng** [comment]
Whoops, no idea why we limited it to 24 characters. Thanks for the PR!

I checked PoE's account creation page and it looks like account names are allowed to be 31 characters long. Would make sense to change our limit to 31 too, so we don't run into this problem again.

**Comment by ImaginaryDevelopment** [comment]
Ok, I guess you found an easier way, I'm having some code search the poe stash api for the longest account name.
Would you be up for/ok with a submission that added or migrated some code to an F# assembly/project in the solution?

I'll update the files to 31

**Comment by brather1ng** [comment]
I never did anything with F# and a mixed language project would make contributing and maintaining more difficult, so I'd rather let it stay C#-only. But that's just my opinion. @EmmittJ and @MLanghof, do you have experience with F#?

**Comment by MLanghof** [comment]
None.

**Comment by EmmittJ** [comment]
My experience is very limited in F#, so I wouldn't say I would be able to support any if it was put into the project. Are there things would directly benefit from assembly? I don't think our process times are very high.

**Pull request merged**
